
"""
TraceShield LLM Provider.

Provides a provider-independent interface for sending
evidence-grounded investigation prompts to an external LLM.

Important:
- The provider receives only the supplied investigation context.
- No blockchain facts are generated locally.
- No wallet ownership is inferred.
- No criminal conclusions are generated by this service.
- API credentials are loaded from environment variables.
- If no provider is configured, the service reports that clearly.
"""

import os
from typing import Any, Dict, Optional

import requests


class LLMProvider:
    """External LLM provider integration."""

    def __init__(self) -> None:
        self.provider = os.getenv(
            "LLM_PROVIDER",
            "not_configured",
        )

        self.api_key = os.getenv("LLM_API_KEY")

        self.model = os.getenv(
            "LLM_MODEL",
            "default-model",
        )

        self.api_url = os.getenv(
            "LLM_API_URL",
            "",
        )

        self.timeout = int(
            os.getenv(
                "LLM_TIMEOUT",
                "60",
            )
        )

    def is_configured(self) -> bool:
        """
        Return whether the provider has the minimum
        configuration required for an external request.
        """

        return bool(
            self.api_key
            and self.provider != "not_configured"
            and self.api_url
        )

    def get_status(self) -> Dict[str, Any]:
        """Return the current provider configuration status."""

        return {
            "configured": self.is_configured(),
            "provider": self.provider,
            "model": self.model,
            "api_url_configured": bool(self.api_url),
        }

    def generate(
        self,
        system_prompt: str,
        user_prompt: str,
    ) -> Dict[str, Any]:
        """
        Send prompts to the configured LLM provider.

        The provider API must accept a JSON payload containing:
        - model
        - system_prompt
        - user_prompt

        The raw provider response is returned without inventing
        additional investigation information.
        """

        if not self.is_configured():
            return {
                "success": False,
                "configured": False,
                "provider": self.provider,
                "model": self.model,
                "message": (
                    "LLM provider is not configured. "
                    "Set LLM_PROVIDER, LLM_API_KEY, "
                    "and LLM_API_URL before making an external request."
                ),
                "response": None,
            }

        if not isinstance(system_prompt, str) or not system_prompt.strip():
            raise ValueError(
                "A non-empty system prompt is required."
            )

        if not isinstance(user_prompt, str) or not user_prompt.strip():
            raise ValueError(
                "A non-empty user prompt is required."
            )

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

        payload = {
            "model": self.model,
            "system_prompt": system_prompt,
            "user_prompt": user_prompt,
        }

        try:
            response = requests.post(
                self.api_url,
                headers=headers,
                json=payload,
                timeout=self.timeout,
            )

            response.raise_for_status()

            try:
                response_data: Optional[Any] = response.json()
            except ValueError:
                response_data = response.text

            return {
                "success": True,
                "configured": True,
                "provider": self.provider,
                "model": self.model,
                "message": "LLM request completed successfully.",
                "response": response_data,
            }

        except requests.RequestException as exc:
            return {
                "success": False,
                "configured": True,
                "provider": self.provider,
                "model": self.model,
                "message": "LLM provider request failed.",
                "error": str(exc),
                "response": None,
            }


llm_provider = LLMProvider()

